apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: hub-class-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName: "{{ ->key_vault_name }}" # Set to the name of your key vault
    cloudName: "" # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects: |
      array:
        - |
          objectName: CLIENT-ID
          objectType: secret              # object types: secret, key, or cert
        - |
          objectName: CLIENT-SECRET
          objectType: secret              # object types: secret, key, or cert
        - |
          objectName: TENANT-NAME
          objectType: secret              # object types: secret, key, or cert
        - |
          objectName: BY-API-ID
          objectType: secret              # object types: secret, key, or cert
    tenantId: "{{ ->key_vault_tenant_id }}" # The tenant ID of the key vault
